// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20210402190702_SeedDataCorrection")]
    partial class SeedDataCorrection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Gender = "F",
                            Name = "Gizmo",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 7,
                            Gender = "M",
                            Name = "Gerry",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 7,
                            Gender = "M",
                            Name = "Geraldo",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 7,
                            Gender = "F",
                            Name = "Guillermo",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 7,
                            Gender = "F",
                            Name = "Gizmo",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
